### ISSUE TITLE
Could the requestId middleware support custom header key?

### ISSUE THREAD

**Issue by wmattei** [saurabh0719/jett#8]
Great lib folks.

I want to start using this on one of my projects, and I was wondering if the `requestId` built-in middleware could support different header key than `X-Request-ID`

If so, I would love to raise a PR doing it (:

**Comment by saurabh0719** [comment]
Hey @wmattei , this sounds useful. Please do issue a PR, I'll be happy to merge it. :)

Just keep in mind that it shouldn't break any existing functionality.
